extends Node

enum CardID {
	ABANDONMENT_OF_LAND,
	ABANDONMENT_OF_OIL_PALM_AREAS,
	ALTERNATIVE_LIVELIHOOD,
	ARTIFICIAL_SALT_LICK,
	BIOLOGICAL_FENCES,
	BUFFER_CROPS,
	CLEARED_BOUNDARIES,
	COMPENSATION,
	CROP_GUARDING,
	EARLY_WARNING_SYSTEM,
	GROW_ELEPHANT_FOOD_IN_THEIR_HABITAT,
	HABITAT_ENRICHMENT,
	INSURANCE,
	LAND_USE_PLANNING,
	LIGHT_BASED_REPELLENT,
	NATURAL_SALT_LICK,
	ORGANIZED_CROP_PROTECTION,
	PHYSICAL_BARRIERS,
	PROTECTED_AREAS,
	REFORESTATION,
	REMOVAL_OF_AGRICULTURAL_SUBSIDIES,
	SMELL_BASED_REPELLENTS,
	SOUND_BASED_REPELLENTS,
	SUSTAINABILITY_PRACTICE,
	WILDLIFE_CORRIDOR,
	ELECTRIC_FENCES,
	ELEPHANT_SANCTUARY,
	IMPROPER_WASTE_MANAGEMENT,
	LABOUR_SHIFT,
	POISON,
	TRANSLOCATION,
	DEFORESTATION,
	DEVELOPMENT,
	PLANTATION_CONVERSION,
	PLANTATION_EXPANSION,
	POACHING,
	POPULATION_CONTROL,
	ROADKILL,
	SELLING_LAND_TO_INDUSTRY,
	URBAN_SPRAWL,
	CORRUPTION,
	DISAGREEMENT,
	DISEASE_STRIKE_ELEPHANTS,
	DISEASE_STRIKE_HUMANS,
	DROUGHT,
	FLOOD,
	FOREST_BURNING,
	OIL_PALM_BURNING,
	SABOTAGING,
	WARMING
}

const CARDS = {
	CardID.ABANDONMENT_OF_LAND: 
		{ "name": "Abandonment of Land", 				"stack": 1, "colour": "green",
		"icons": ["human-dominated land", "human-dominated land", "move to", "forest", "forest"],
		"desc": "Abandoned land that is overgrown by invasive plants. The land can be enriched as forests or as a food area for elephants.", 
		"action": "Using the single tiles, [b]CONVERT[/b] two human-dominated landscape tiles, into two forest tiles." },
	CardID.ABANDONMENT_OF_OIL_PALM_AREAS: 
		{ "name": "Abandonment of Oil Palm Areas",		"stack": 1, "colour": "green",
		"icons": ["plantation", "plantation", "move to", "forest", "forest"],
		"desc": "Neglected plantation area that is overgrown by invasive plants. The area can be enriched as forests or as a food area for elephants. ", 
		"action": "Using the single tiles, [b]CONVERT[/b] two plantation tiles, into two forest tiles." },
	CardID.ALTERNATIVE_LIVELIHOOD: 
		{ "name": "Alternative Livelihood", 			"stack": 1, "colour": "green",
		"icons": ["add","elephant","add","villager","villager"],
		"flip": "elephant",
		"desc": "Plantation or community obtain income from other economic activities that are wildlife and environment- friendly. For example, selling honey from beehives used as repellents.",
		"action": "[b]ADD[/b] one elephant and [b]ADD[/b] two villagers."},
	CardID.ARTIFICIAL_SALT_LICK: 
		{ "name": "Artificial Salt Lick", 				"stack": 1, "colour": "green",
		"icons": ["add","villager","villager","add","elephant"],
		"desc": "Manmade saltlicks created away from human settlements may deter elephants from entering plantations.", 
		"action": "[b]ADD[/b] two villagers and one elephant." },
	CardID.BIOLOGICAL_FENCES: 
		{ "name": "Biological Fences", 					"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.BUFFER_CROPS: 
		{ "name": "Buffer Crops", 						"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.CLEARED_BOUNDARIES: 
		{ "name": "Cleared Boundaries", 				"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.COMPENSATION: 
		{ "name": "Compensation", 						"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.CROP_GUARDING: 
		{ "name": "Crop Guarding", 						"stack": 1, "colour": "green", 
		"icons": ["plantation", "move away", "elephant", "elephant"], 
		"desc": "Keeping elephants away through human presence and patrolling.",
		"action": "[b]Move[/b] two elephant [b][color=red]one[/color][/b] tile away from the plantation."},
	CardID.EARLY_WARNING_SYSTEM: 
		{ "name": "Early Warning System", 				"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.GROW_ELEPHANT_FOOD_IN_THEIR_HABITAT: 
		{ "name": "Grow Elephant Food in their Habitat", "stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.HABITAT_ENRICHMENT: 
		{ "name": "Habitat Enrichment", 				"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.INSURANCE: 
		{ "name": "Insurance", 							"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.LAND_USE_PLANNING: 
		{ "name": "Land-Use Planning", 					"stack": 2, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.LIGHT_BASED_REPELLENT: 
		{ "name": "Light Based Repellent", 				"stack": 1, "colour": "green",
		"icons": ["empty","human-dominated land", "plantation", "move away", "elephant","empty"],
		"desc": "Keeping elephants away using light e.g., LED lights, bonfire, torches and solar powered lamps.",
		"action": "[b]MOVE[/b] [color=red]one[/color] elephant one tile away from the plantation or from human-dominated landscapes."},
	CardID.NATURAL_SALT_LICK: 
		{ "name": "Natural Salt Lick", 					"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.ORGANIZED_CROP_PROTECTION: 
		{ "name": "Organized Crop Protection", 			"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.PHYSICAL_BARRIERS: 
		{ "name": "Physical Barriers", 					"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.PROTECTED_AREAS: 
		{ "name": "Protected Areas", 					"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.REFORESTATION: 
		{ "name": "Reforestation",						"stack": 3, "colour": "green",
		"icons": [],
		"desc": "", "action": ""},
	CardID.REMOVAL_OF_AGRICULTURAL_SUBSIDIES: 
		{ "name": "Removal of Agricultural Subsidies", 	"stack": 2, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.SMELL_BASED_REPELLENTS: 
		{ "name": "Smell-Based Repellents", 			"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.SOUND_BASED_REPELLENTS: 
		{ "name": "Sound-Based Repellents", 			"stack": 1, "colour": "green",
		"desc": "Keeping elephants away through noisemaking e.g., firecrackers.",
		"action": "[b]MOVE[/b] [color=red]one[/color] elephant one tile away from the plantation or from human-dominated landscapes."},
	CardID.SUSTAINABILITY_PRACTICE: 
		{ "name": "Sustainability Practice", 			"stack": 3, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.WILDLIFE_CORRIDOR: 
		{ "name": "Wildlife Corridor", 					"stack": 1, "colour": "green",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.ELECTRIC_FENCES: 
		{ "name": "Electric Fences",					"stack": 3, "colour": "yellow",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.ELEPHANT_SANCTUARY: 
		{ "name": "Elephant Sanctuary", 				"stack": 3, "colour": "yellow",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.IMPROPER_WASTE_MANAGEMENT: 
		{ "name": "Improper Waste Management", 			"stack": 2, "colour": "yellow",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.LABOUR_SHIFT: 
		{ "name": "Labour Shift", 						"stack": 1, "colour": "yellow",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.POISON: 
		{ "name": "Poison", 							"stack": 2, "colour": "yellow",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.TRANSLOCATION: 
		{ "name": "Translocation", 						"stack": 2, "colour": "yellow",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.DEFORESTATION: 
		{ "name": "Deforestation", 						"stack": 2, "colour": "red",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.DEVELOPMENT: 
		{ "name": "Development", 						"stack": 3, "colour": "red",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.PLANTATION_CONVERSION: 
		{ "name": "Plantation Conversion", 				"stack": 1, "colour": "red",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.PLANTATION_EXPANSION: 
		{ "name": "Plantation Expansion", 				"stack": 1, "colour": "red",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.POACHING: 
		{ "name": "Poaching", 							"stack": 2, "colour": "red",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.POPULATION_CONTROL: 
		{ "name": "Population Control", 				"stack": 1, "colour": "red",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.ROADKILL: 
		{ "name": "Roadkill", 							"stack": 1, "colour": "red",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.SELLING_LAND_TO_INDUSTRY: 
		{ "name": "Selling Land to Industry", 			"stack": 2, "colour": "red",
		"icons": [],
		"desc": "", 
		"action": "" },
	CardID.URBAN_SPRAWL: 
		{ "name": "Urban Sprawl", 						"stack": 2, "colour": "red",
		"icons": [],
		"desc": "", 
		"action": "" },
		CardID.CORRUPTION: 
		{ "name": "Corruption", 						"stack": 1, "colour": "black",
		"icons": ["steal action card"],
		"desc": "This is an abuse of money or power for private gain.", 
		"action": "[b]STEAL[/b] one played action card from another player and play it during this turn." },
	CardID.DISAGREEMENT: 
		{ "name": "Disagreement", 						"stack": 1, "colour": "black",
		"icons": ["return played card"],
		"desc": "An argument that results in the roles not working together.", 
		"action": "All players except the current player are to [b]RETURN[/b] one of their played coloured action cards into their hand." },
	CardID.DISEASE_STRIKE_ELEPHANTS: 
		{ "name": "Disease Strike Elephants", 			"stack": 1, "colour": "black",
		"icons": ["remove elephants"],
		"desc": "Bacteria that spreads from food or interactions among elephants causing serious illness and death.", 
		"action": "[b]REMOVE[/b] three elephants." },
	CardID.DISEASE_STRIKE_HUMANS: 
		{ "name": "Disease Strike Humans", 				"stack": 1, "colour": "black",
		"icons": ["del villager", "del villager", "del villager"],
		"desc": "The spread of viruses from wildlife (zoonotic) that cause death.", 
		"action": "[b]REMOVE[/b] three villagers." },
	CardID.DROUGHT: 
		{ "name": "Drought", 							"stack": 1, "colour": "black",
		"icons": ["all elephants", "move to","human-dominated land", "plantation"],
		"desc": "Prolonged dry weather without rain causes shortages of water and food resources in certain areas.", 
		"action": "All elephants [b]MOVE[/b] [color=red]two[color] towards plantation or human-dominated landscapes." },
	CardID.FLOOD: 
		{ "name": "Flood", 								"stack": 1, "colour": "black",
		"icons": ["all elephants", "move to","human-dominated land", "plantation"],
		"desc": "Rivers and lakes within forest overflow with water. This causes elephants to move to higher ground.", 
		"action": "All elephants [b]MOVE[/b] [color=red]two[color] towards plantation or human-dominated landscape." },
	CardID.FOREST_BURNING: {
		 "name": "Forest Burning", 						"stack": 1, "colour": "black",
		"icons": ["all elephants", "move to","human-dominated land", "plantation"],
		"desc": "Clearing forests using fire causes injuries and loss of wildlife habitat. Rampant burning triggers haze problems.", 
		"action": "All elephants [b]MOVE[/b] [color=red]two[color] towards plantation or human-dominated landscape." },
	CardID.OIL_PALM_BURNING: 
		{ "name": "Oil Palm Burning", 					"stack": 1, "colour": "black",
		"icons": ["del villager", "del villager", "del villager"],
		"desc": "The clearing of oil palm plantations illegally and uncontrollably using fire.", 
		"action": "[b]REMOVE[/b] three villagers." },
	CardID.SABOTAGING: 
		{ "name": "Sabotaging", 						"stack": 1, "colour": "black",
		"icons": [],
		"desc": "The purposeful destruction of someone's property causing them to fall behind.", 
		"action": "[b]SKIP[/b] the next player's turn." },
	CardID.WARMING: 
		{ "name": "Warming", 							"stack": 1, "colour": "black",
		"icons": ["del villager", "del elephant"],
		"desc": "An increase in the Earth's temperature causes hot and dry weather or severe off-season rain.",
		"action": "[b]REMOVE[/b] one villager and one elephant." }
}
